// Mock data for Gallery 1882 static prototypes
// Note: mockExhibitions kept for backward compatibility, mockHappenings matches Payload format

export const mockHappenings = [
  {
    title: 'Shoreline Reflections',
    startDate: '2024-03-15T10:00:00Z',
    endDate: '2024-05-20T18:00:00Z',
    description:
      'A contemplative exploration of light and water along the Indiana Dunes shoreline.',
    category: 'Exhibition',
    featuredPersonName: 'Sarah Chen',
    heroImage: '/media/test-art.jpg',
    featured: true,
    isActive: false,
  },
  {
    title: 'Industrial Echoes',
    startDate: '2024-06-01T10:00:00Z',
    endDate: '2024-08-15T18:00:00Z',
    description:
      'Mixed media works examining the relationship between industry and nature in the Great Lakes region.',
    category: 'Exhibition',
    featuredPersonName: 'Marcus Rodriguez',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Dune Formations',
    startDate: '2024-09-01T10:00:00Z',
    endDate: '2024-11-30T18:00:00Z',
    description: 'Sculptural interpretations of the ever-changing dune landscapes.',
    category: 'Exhibition',
    featuredPersonName: 'Elena Kowalski',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Future Visions',
    startDate: '2024-12-01T10:00:00Z',
    endDate: '2025-02-28T18:00:00Z',
    description: 'Geometric abstractions exploring the future of form and color.',
    category: 'Exhibition',
    featuredPersonName: 'Tomma Abts',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Performance Spaces',
    startDate: '2024-01-15T10:00:00Z',
    endDate: '2024-03-10T18:00:00Z',
    description: 'Retrospective of pioneering performance and architectural interventions.',
    category: 'Exhibition',
    featuredPersonName: 'Vito Acconci',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Sonic Sculptures',
    startDate: '2023-10-01T10:00:00Z',
    endDate: '2023-12-15T18:00:00Z',
    description: 'Musical sculptures exploring African American history and culture.',
    category: 'Exhibition',
    featuredPersonName: 'Terry Adkins',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Spiritual Abstractions',
    startDate: '2023-07-01T10:00:00Z',
    endDate: '2023-09-30T18:00:00Z',
    description: 'Mystical paintings that predated the official birth of abstract art.',
    category: 'Exhibition',
    featuredPersonName: 'Hilma af Klint',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Cultural Intersections',
    startDate: '2023-04-01T10:00:00Z',
    endDate: '2023-06-30T18:00:00Z',
    description: 'Large-scale works exploring Nigerian and American cultural intersections.',
    category: 'Exhibition',
    featuredPersonName: 'Njideka Akunyili Crosby',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Transformation Series',
    startDate: '2023-01-15T10:00:00Z',
    endDate: '2023-03-31T18:00:00Z',
    description: 'Large-scale installations made from discarded materials transformed into art.',
    category: 'Exhibition',
    featuredPersonName: 'El Anatsui',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Minimalist Forms',
    startDate: '2022-10-01T10:00:00Z',
    endDate: '2022-12-31T18:00:00Z',
    description: 'Floor-based sculptures using industrial materials in minimalist arrangements.',
    category: 'Exhibition',
    featuredPersonName: 'Carl Andre',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Natural Forces',
    startDate: '2022-07-01T10:00:00Z',
    endDate: '2022-09-30T18:00:00Z',
    description: 'Arte Povera works exploring natural forces and materials.',
    category: 'Exhibition',
    featuredPersonName: 'Giovanni Anselmo',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Portrait Studies',
    startDate: '2022-04-01T10:00:00Z',
    endDate: '2022-06-30T18:00:00Z',
    description: 'Raw, emotionally charged portraits and figure studies.',
    category: 'Exhibition',
    featuredPersonName: 'Francis Bacon',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Street Interventions',
    startDate: '2022-01-15T10:00:00Z',
    endDate: '2022-03-31T18:00:00Z',
    description: 'Satirical and subversive works commenting on politics and society.',
    category: 'Exhibition',
    featuredPersonName: 'Banksy',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Neo-Expressionist Works',
    startDate: '2021-10-01T10:00:00Z',
    endDate: '2021-12-31T18:00:00Z',
    description: 'Large-scale paintings from the 1980s neo-expressionist movement.',
    category: 'Exhibition',
    featuredPersonName: 'Jean-Michel Basquiat',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Sculptural Narratives',
    startDate: '2021-07-01T10:00:00Z',
    endDate: '2021-09-30T18:00:00Z',
    description: 'Large-scale sculptures exploring themes of sexuality and family.',
    category: 'Exhibition',
    featuredPersonName: 'Louise Bourgeois',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Abstract Forms',
    startDate: '2021-04-01T10:00:00Z',
    endDate: '2021-06-30T18:00:00Z',
    description: 'Pioneering abstract sculptures that influenced modern art.',
    category: 'Exhibition',
    featuredPersonName: 'Constantin Brancusi',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Language and Art',
    startDate: '2021-01-15T10:00:00Z',
    endDate: '2021-03-31T18:00:00Z',
    description: 'Works exploring the relationship between art and language.',
    category: 'Exhibition',
    featuredPersonName: 'Marcel Broodthaers',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Kinetic Sculptures',
    startDate: '2020-10-01T10:00:00Z',
    endDate: '2020-12-31T18:00:00Z',
    description: 'Innovative mobiles and stabiles in motion.',
    category: 'Exhibition',
    featuredPersonName: 'Alexander Calder',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Personal Narratives',
    startDate: '2020-07-01T10:00:00Z',
    endDate: '2020-09-30T18:00:00Z',
    description: 'Photography, text, and performance exploring personal themes.',
    category: 'Exhibition',
    featuredPersonName: 'Sophie Calle',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Feminist Art Movement',
    startDate: '2020-04-01T10:00:00Z',
    endDate: '2020-06-30T18:00:00Z',
    description: 'Large-scale collaborative installations from the feminist art movement.',
    category: 'Exhibition',
    featuredPersonName: 'Judy Chicago',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Environmental Art',
    startDate: '2020-01-15T10:00:00Z',
    endDate: '2020-03-31T18:00:00Z',
    description: 'Large-scale environmental art installations.',
    category: 'Exhibition',
    featuredPersonName: 'Christo',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Abstract Expressionism',
    startDate: '2019-10-01T10:00:00Z',
    endDate: '2019-12-31T18:00:00Z',
    description: 'Gestural brushwork and abstract expressionist paintings.',
    category: 'Exhibition',
    featuredPersonName: 'Willem de Kooning',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Dada and Readymades',
    startDate: '2019-07-01T10:00:00Z',
    endDate: '2019-09-30T18:00:00Z',
    description: 'Works challenging conventional notions of art and aesthetics.',
    category: 'Exhibition',
    featuredPersonName: 'Marcel Duchamp',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Portrait Paintings',
    startDate: '2019-04-01T10:00:00Z',
    endDate: '2019-06-30T18:00:00Z',
    description: 'Emotionally charged portraits and figure paintings.',
    category: 'Exhibition',
    featuredPersonName: 'Marlene Dumas',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Autobiographical Art',
    startDate: '2019-01-15T10:00:00Z',
    endDate: '2019-03-31T18:00:00Z',
    description: 'Confessional and autobiographical works in various media.',
    category: 'Exhibition',
    featuredPersonName: 'Tracey Emin',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Psychological Portraits',
    startDate: '2018-10-01T10:00:00Z',
    endDate: '2018-12-31T18:00:00Z',
    description: 'Intense, psychological portraits and figure studies.',
    category: 'Exhibition',
    featuredPersonName: 'Lucian Freud',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Color Field Painting',
    startDate: '2018-07-01T10:00:00Z',
    endDate: '2018-09-30T18:00:00Z',
    description: 'Abstract expressionist color field paintings.',
    category: 'Exhibition',
    featuredPersonName: 'Helen Frankenthaler',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Existential Sculptures',
    startDate: '2018-04-01T10:00:00Z',
    endDate: '2018-06-30T18:00:00Z',
    description: 'Elongated, existential figures in bronze.',
    category: 'Exhibition',
    featuredPersonName: 'Alberto Giacometti',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Self-Portrait Series',
    startDate: '2018-01-15T10:00:00Z',
    endDate: '2018-03-31T18:00:00Z',
    description: 'Self-portraits inspired by Mexican folk art.',
    category: 'Exhibition',
    featuredPersonName: 'Frida Kahlo',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
  {
    title: 'Abstract Compositions',
    startDate: '2017-10-01T10:00:00Z',
    endDate: '2017-12-31T18:00:00Z',
    description: 'Pioneering abstract compositions and color theory.',
    category: 'Exhibition',
    featuredPersonName: 'Wassily Kandinsky',
    heroImage: '/media/test-art.jpg',
    featured: false,
    isActive: false,
  },
]

// Keep old mockExhibitions for backward compatibility
export const mockExhibitions = mockHappenings.map((h, index) => ({
  id: String(index + 1),
  title: h.title,
  artist: h.featuredPersonName || '',
  startDate: h.startDate.split('T')[0],
  endDate: h.endDate?.split('T')[0] || '',
  description: h.description,
  image: h.heroImage,
  featured: h.featured,
}))

export const mockArtists = [
  {
    name: 'Sarah Chen',
    bio: 'Sarah Chen is a landscape photographer based in Chicago, known for her intimate studies of the Great Lakes region.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Marcus Rodriguez',
    bio: 'Marcus Rodriguez creates large-scale installations that explore the intersection of urban and natural environments.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Elena Kowalski',
    bio: 'Elena Kowalski is a sculptor whose work examines the relationship between geological time and human experience.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Tomma Abts',
    bio: 'Tomma Abts is a German painter known for her abstract geometric works that explore the relationship between form and color.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Vito Acconci',
    bio: 'Vito Acconci was a pioneering performance artist and architect whose work challenged conventional boundaries of art and space.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Terry Adkins',
    bio: 'Terry Adkins was an American sculptor and musician whose work explored African American history and culture through found objects.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Hilma af Klint',
    bio: 'Hilma af Klint was a Swedish artist and mystic whose abstract paintings predated the official birth of abstract art.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Njideka Akunyili Crosby',
    bio: 'Njideka Akunyili Crosby creates large-scale works that explore the intersection of Nigerian and American cultures.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'El Anatsui',
    bio: 'El Anatsui is a Ghanaian sculptor known for his large-scale installations made from discarded bottle caps and aluminum.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Carl Andre',
    bio: 'Carl Andre is an American minimalist sculptor known for his floor-based works using industrial materials.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Giovanni Anselmo',
    bio: 'Giovanni Anselmo was an Italian artist associated with Arte Povera, known for his works exploring natural forces and materials.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Francis Bacon',
    bio: 'Francis Bacon was a British painter known for his raw, emotionally charged portraits and figure studies.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Banksy',
    bio: 'Banksy is a British street artist whose satirical and subversive works comment on politics, culture, and society.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Jean-Michel Basquiat',
    bio: 'Jean-Michel Basquiat was an American artist who rose to fame in the 1980s with his neo-expressionist paintings.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Louise Bourgeois',
    bio: 'Louise Bourgeois was a French-American artist known for her large-scale sculptures and installations exploring themes of sexuality and family.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Constantin Brancusi',
    bio: 'Constantin Brancusi was a Romanian sculptor who pioneered abstract sculpture and influenced modern art.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Marcel Broodthaers',
    bio: 'Marcel Broodthaers was a Belgian artist whose work explored the relationship between art and language.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Alexander Calder',
    bio: 'Alexander Calder was an American sculptor known for his innovative mobiles and stabiles.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Sophie Calle',
    bio: 'Sophie Calle is a French artist whose work combines photography, text, and performance to explore personal and social themes.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Judy Chicago',
    bio: 'Judy Chicago is an American feminist artist known for her large-scale collaborative art installations.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Christo',
    bio: 'Christo was a Bulgarian artist known for his large-scale environmental art installations with his wife Jeanne-Claude.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Willem de Kooning',
    bio: 'Willem de Kooning was a Dutch-American abstract expressionist painter known for his gestural brushwork.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Marcel Duchamp',
    bio: 'Marcel Duchamp was a French-American artist whose work challenged conventional notions of art and aesthetics.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Marlene Dumas',
    bio: 'Marlene Dumas is a South African painter known for her emotionally charged portraits and figure paintings.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Tracey Emin',
    bio: 'Tracey Emin is a British artist known for her confessional and autobiographical works in various media.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Lucian Freud',
    bio: 'Lucian Freud was a British painter known for his intense, psychological portraits and figure studies.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Helen Frankenthaler',
    bio: 'Helen Frankenthaler was an American abstract expressionist painter known for her color field paintings.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Alberto Giacometti',
    bio: 'Alberto Giacometti was a Swiss sculptor and painter known for his elongated, existential figures.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Frida Kahlo',
    bio: 'Frida Kahlo was a Mexican painter known for her self-portraits and works inspired by Mexican folk art.',
    image: '/media/test-artist.jpg',
  },
  {
    name: 'Wassily Kandinsky',
    bio: 'Wassily Kandinsky was a Russian painter and art theorist who pioneered abstract art.',
    image: '/media/test-artist.jpg',
  },
]

export const mockEvents = [
  {
    id: '1',
    title: 'Opening Reception: Shoreline Reflections',
    date: '2024-03-15',
    time: '6:00 PM - 8:00 PM',
    description: "Join us for the opening of Sarah Chen's new exhibition.",
    type: 'opening',
  },
  {
    id: '2',
    title: 'Artist Talk: Marcus Rodriguez',
    date: '2024-06-15',
    time: '2:00 PM - 3:00 PM',
    description: 'The artist discusses his process and inspiration for Industrial Echoes.',
    type: 'talk',
  },
  {
    id: '3',
    title: 'Gallery Hours',
    date: '2024-03-01',
    time: '10:00 AM - 6:00 PM',
    description: 'Regular gallery hours: Wednesday through Sunday, 10 AM to 6 PM.',
    type: 'info',
  },
]

export const mockPress = [
  {
    id: '1',
    title: 'Gallery 1882 Opens with Stunning Dune-Inspired Exhibition',
    publication: 'Chicago Tribune',
    date: '2024-03-20',
    url: '#',
  },
  {
    id: '2',
    title: 'New Art Space Celebrates Indiana Dunes Heritage',
    publication: 'Art in America',
    date: '2024-03-18',
    url: '#',
  },
  {
    id: '3',
    title: 'Gallery 1882: Where Art Meets Nature',
    publication: 'South Bend Tribune',
    date: '2024-03-15',
    url: '#',
  },
]

export const mockGalleryInfo = {
  name: 'Gallery 1882',
  tagline: 'Contemporary Art in the Heart of the Indiana Dunes',
  description:
    'Gallery 1882 is a contemporary art space dedicated to showcasing works that explore the intersection of art, nature, and the unique landscape of the Indiana Dunes region.',
  address: '123 Dune Drive, Chesterton, IN 46304',
  phone: '(219) 555-0188',
  email: 'info@gallery1882.org',
  hours: 'Wednesday - Sunday, 10 AM - 6 PM',
  admission: 'Free',
}

// Visit Section Data
export const mockVisitSection = {
  title: 'Escape to the Duneland',
  description:
    'Located under an hours drive from Chicago, Gallery 1882, in the heart of Chesterton, Indiana is the gateway to the Indiana Dunes National Park. Always open, always free, always inspiring.',
  image: '/media/test-space.jpg',
  ctaText: 'Plan Your Visit',
  ctaUrl: '/visit',
}

// Artist Feature Data
export const mockFeaturedArtist = {
  id: '1',
  name: 'Sarah Chen',
  title: 'Shoreline Reflections',
  bio: 'Sarah Chen is a landscape photographer whose intimate studies of the Great Lakes region capture the ephemeral beauty of light and water. Her work invites viewers to slow down and contemplate the subtle interactions between natural elements.',
  image: '/media/test-artist.jpg',
  exhibitionId: '1',
  artistSlug: 'sarah-chen',
}

// Journal Banner Data
export const mockJournalBanner = {
  headline: 'Stay Connected',
  subheadline:
    'Subscribe to our journal for exclusive artist interviews, behind-the-scenes content, and insights into contemporary art practice.',
  ctaText: 'Subscribe to Journal',
  ctaUrl: '/news',
}

// Mission Section Data
export const mockMission = {
  statement:
    'We believe art has the power to transform our understanding of place, to bridge the gap between human creativity and the natural world, and to inspire new ways of seeing the landscape we call home.',
  ctaText: 'Learn More About Us',
  ctaUrl: '/about',
}
