import type { Media } from '@/payload-types'
import type { MediaWithSizes } from '@/types/media-sizes'

import { getMediaUrl } from './getMediaUrl'

/**
 * Available pre-generated image sizes, ordered smallest to largest.
 * These are WebP images generated by the background job.
 */
const SIZE_ORDER = ['square', 'small', 'medium', 'large', 'xlarge'] as const
type SizeName = (typeof SIZE_ORDER)[number]

/**
 * Maximum widths for each size (matches generateImageSizes job config).
 */
const SIZE_WIDTHS: Record<SizeName, number> = {
  square: 500,
  small: 600,
  medium: 900,
  large: 1400,
  xlarge: 1920,
}

/**
 * Resolves the best pre-generated WebP URL for a media object at a given display width.
 *
 * Falls back to the original URL if no suitable size is available
 * (e.g. processing is still pending).
 *
 * @param media - Payload Media object (may include background-generated sizes)
 * @param targetWidth - Desired display width in pixels (picks the smallest size >= this)
 * @returns URL string ready for use in `next/image` src, or empty string if no URL
 */
export function resolveOptimizedUrl(
  media: Media | MediaWithSizes | null | undefined,
  targetWidth: number = 1400,
): string {
  if (!media || typeof media !== 'object') return ''

  const cacheTag = media.updatedAt
  const sizes = (media as MediaWithSizes).sizes

  if (sizes) {
    // Find the smallest pre-generated size that is >= targetWidth
    for (const name of SIZE_ORDER) {
      if (SIZE_WIDTHS[name] >= targetWidth) {
        const sizeData = sizes[name]
        if (sizeData?.url) {
          return getMediaUrl(sizeData.url, cacheTag)
        }
      }
    }

    // If no size is large enough, use the largest available
    for (let i = SIZE_ORDER.length - 1; i >= 0; i--) {
      const name = SIZE_ORDER[i]
      const sizeData = sizes[name]
      if (sizeData?.url) {
        return getMediaUrl(sizeData.url, cacheTag)
      }
    }
  }

  // Fallback to original URL
  return getMediaUrl(media.url, cacheTag)
}
