/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    artists: Artist;
    happenings: Happening;
    'happening-types': HappeningType;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    happenings: HappeningsSelect<false> | HappeningsSelect<true>;
    'happening-types': HappeningTypesSelect<false> | HappeningTypesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    visit: Visit;
    policies: Policy;
    'our-story': OurStory;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    visit: VisitSelect<false> | VisitSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    'our-story': OurStorySelect<false> | OurStorySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      generateImageSizes: TaskGenerateImageSizes;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  artists?: (string | Artist)[] | null;
  happenings?: (string | Happening)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Max file size: 50MB. Accepted formats: JPEG, PNG, WebP, GIF, MP4, WebM. Images larger than 2560px are auto-resized. Images are automatically converted to WebP for optimal performance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and SEO (e.g. "Artist painting in gallery studio")
   */
  alt?: string | null;
  /**
   * Photo credit or caption displayed wherever this image appears on the site
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Details about automatic processing applied to this upload
   */
  processingInfo?: string | null;
  /**
   * Status of background image size generation
   */
  processingStatus?: ('pending' | 'processing' | 'complete' | 'failed') | null;
  /**
   * Error details from image processing
   */
  processingError?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: string;
  name: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Gallery of artist works. Photo captions/credits are managed on each Media document.
   */
  works?:
    | {
        image: string | Media;
        /**
         * Artwork title. The photo caption/credit comes from the Media document.
         */
        title?: string | null;
        /**
         * Tag which shows/exhibitions this work appears in
         */
        happenings?: (string | Happening)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Artist's personal website
   */
  website?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'twitter' | 'facebook' | 'linkedin' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happenings".
 */
export interface Happening {
  id: string;
  title: string;
  /**
   * Optional subtitle displayed between the title and artist list
   */
  subcaption?: string | null;
  /**
   * Determines how dates are displayed. Date Range types show "March 16–June 20"; Date+Time types show "March 28 from 7–9pm".
   */
  type: string | HappeningType;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (string | null) | Media;
  /**
   * For Date Range types, only the date portion is displayed. For Date+Time types, both date and time are shown.
   */
  startDate: string;
  /**
   * For Date Range types, displayed as the end of the range. For Date+Time types, only the end time is shown (same day assumed).
   */
  endDate?: string | null;
  /**
   * Enable to manually override automatic isActive calculation
   */
  isActiveOverride?: boolean | null;
  /**
   * Automatically calculated based on dates unless overridden
   */
  isActive?: boolean | null;
  /**
   * Artists involved in this happening (supports multiple for group shows)
   */
  artists?: (string | Artist)[] | null;
  /**
   * Contact information displayed below the works grid (e.g. gallery contact, sales inquiries)
   */
  contactInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happening-types".
 */
export interface HappeningType {
  id: string;
  name: string;
  /**
   * URL-safe identifier, auto-generated from name
   */
  slug: string;
  /**
   * Controls how dates are formatted on the frontend for happenings of this type
   */
  dateDisplayMode: 'date-range' | 'datetime';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: string | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateImageSizes' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'generateImageSizes' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'artists';
        value: string | Artist;
      } | null)
    | ({
        relationTo: 'happenings';
        value: string | Happening;
      } | null)
    | ({
        relationTo: 'happening-types';
        value: string | HappeningType;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  artists?: T;
  happenings?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  processingInfo?: T;
  processingStatus?: T;
  processingError?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  image?: T;
  works?:
    | T
    | {
        image?: T;
        title?: T;
        happenings?: T;
        id?: T;
      };
  website?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happenings_select".
 */
export interface HappeningsSelect<T extends boolean = true> {
  title?: T;
  subcaption?: T;
  type?: T;
  description?: T;
  heroImage?: T;
  startDate?: T;
  endDate?: T;
  isActiveOverride?: T;
  isActive?: T;
  artists?: T;
  contactInfo?: T;
  featured?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "happening-types_select".
 */
export interface HappeningTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  dateDisplayMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    hero: {
      type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
      richText?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      links?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?: {
                relationTo: 'posts';
                value: string | Post;
              } | null;
              url?: string | null;
              label: string;
              /**
               * Choose how the link should be rendered.
               */
              appearance?: ('default' | 'outline') | null;
            };
            id?: string | null;
          }[]
        | null;
      media?: (string | null) | Media;
    };
  };
  /**
   * Upload an MP4 or WebM video for the hero background. Leave blank to show no video.
   */
  heroVideo?: (string | null) | Media;
  /**
   * Optional poster image shown while the video loads. Should be a still frame or preview of the video.
   */
  heroVideoPoster?: (string | null) | Media;
  /**
   * Small icon/logo displayed above the mission statement
   */
  missionIcon?: (string | null) | Media;
  missionStatement?: string | null;
  missionCtaText?: string | null;
  missionCtaUrl?: string | null;
  /**
   * Select an artist to feature on the homepage
   */
  featuredArtist?: (string | null) | Artist;
  /**
   * Optional: override the artist's default image for the homepage display
   */
  featuredArtistImage?: (string | null) | Media;
  /**
   * Button text prefix before the artist's first name (defaults to "More About")
   */
  featuredArtistCtaPrefix?: string | null;
  /**
   * Optional: custom blurb for the homepage (overrides artist bio)
   */
  featuredArtistDescription?: string | null;
  /**
   * Toggle the "Plan Your Visit" promo card on the homepage
   */
  visitSectionEnabled?: boolean | null;
  /**
   * Custom title for the homepage visit promo card. If empty, defaults to gallery description from Space.
   */
  visitTitle?: string | null;
  visitDescription?: string | null;
  visitImage?: (string | null) | Media;
  visitCtaText?: string | null;
  visitCtaUrl?: string | null;
  /**
   * Headline for the newsletter popup (defaults to "Opening Soon")
   */
  popupHeadline?: string | null;
  /**
   * Description text for the newsletter popup (defaults to launch announcement copy)
   */
  popupDescription?: string | null;
  /**
   * Submit button text (defaults to "Subscribe")
   */
  popupButtonText?: string | null;
  /**
   * Message shown after successful signup (defaults to "You've been added to the newsletter!")
   */
  popupSuccessMessage?: string | null;
  /**
   * Toggle the What's Happening section on the homepage
   */
  whatsHappeningEnabled?: boolean | null;
  /**
   * Override the section title (defaults to "What's Happening?")
   */
  whatsHappeningTitle?: string | null;
  /**
   * Show the decorative icon next to the section heading
   */
  whatsHappeningIcon?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit".
 */
export interface Visit {
  id: string;
  heroImage?: (string | null) | Media;
  hours?: {
    caption?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Note about last admission, holidays, etc.
     */
    note?: string | null;
    specialHoursTitle?: string | null;
    /**
     * Holiday or temporary hour changes. Shown only on the Visit page, alongside regular hours from Space.
     */
    specialHours?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Toggle visibility of the Admission section on the Visit page
   */
  showAdmissionSection?: boolean | null;
  /**
   * Detailed admission info (general & group visits). Shown only on the Visit page when enabled. For the short footer text, edit Space > Admission instead.
   */
  admission?: {
    caption?: string | null;
    title?: string | null;
    description?: string | null;
    generalAdmissionTitle?: string | null;
    generalAdmissionDescription?: string | null;
    generalAdmissionFeatures?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    groupVisitTitle?: string | null;
    groupVisitDescription?: string | null;
    groupVisitFeatures?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  location?: {
    caption?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Heading above the address (defaults to "Address"). The address itself is pulled from SiteSettings > Gallery Info.
     */
    addressLabel?: string | null;
    /**
     * Link to Google Maps directions (e.g. https://maps.google.com/?q=Gallery+1882). Displays a "Get Directions" button.
     */
    googleMapsUrl?: string | null;
    /**
     * Heading above the parking info (defaults to "Parking")
     */
    parkingLabel?: string | null;
    parkingDescription?: string | null;
    parkingFeatures?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    directions?:
      | {
          title: string;
          content: string;
          style?: ('default' | 'lake' | 'dark') | null;
          id?: string | null;
        }[]
      | null;
  };
  chesterton?: {
    caption?: string | null;
    title?: string | null;
    description?: string | null;
    features?:
      | {
          title: string;
          description: string;
          icon?: ('location' | 'building' | 'heart') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Toggle visibility of the "Explore the Duneland Community" section
   */
  dunelandCommunityEnabled?: boolean | null;
  dunelandCommunity?: {
    caption?: string | null;
    title?: string | null;
    description?: string | null;
  };
  faqsSection?: {
    caption?: string | null;
    title?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: string;
  /**
   * Full privacy policy content. Leave empty to display the default hardcoded policy.
   */
  privacyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  privacyLastUpdated?: string | null;
  /**
   * Full cookie policy content. Leave empty to display the default hardcoded policy.
   */
  cookiesContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cookiesLastUpdated?: string | null;
  /**
   * Full terms and conditions content.
   */
  termsContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsLastUpdated?: string | null;
  /**
   * Land acknowledgement statement.
   */
  landAcknowledgementContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story".
 */
export interface OurStory {
  id: string;
  /**
   * Up to 10 photos displayed in the carousel. Drag to reorder.
   */
  photos?:
    | {
        image: string | Media;
        /**
         * Editorial caption for the carousel, shown below the photo on the Our Story page
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The gallery story content, displayed below the photo carousel
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  name: string;
  tagline?: string | null;
  description?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Legacy field — no longer displayed. Use Operating Hours below instead.
   */
  hours?: string | null;
  /**
   * Regular operating hours. Shown in the footer and used as the base for the Visit page.
   */
  structuredHours?:
    | {
        day: '0' | '1' | '2' | '3' | '4' | '5' | '6';
        /**
         * Opening time in 24h format, e.g. "10:00"
         */
        open: string;
        /**
         * Closing time in 24h format, e.g. "18:00"
         */
        close: string;
        id?: string | null;
      }[]
    | null;
  admission?: string | null;
  pageTitles?: {
    /**
     * Title shown at the top of the Artists page
     */
    artists?: string | null;
    /**
     * Title shown at the top of the Happenings page
     */
    happenings?: string | null;
    /**
     * Title shown at the top of the News page
     */
    news?: string | null;
    /**
     * Title shown at the top of the Visit page
     */
    visit?: string | null;
    /**
     * Title shown at the top of the Our Story page
     */
    ourStory?: string | null;
  };
  labels?: {
    /**
     * Caption shown above the featured artist on the homepage
     */
    featuredArtist?: string | null;
    /**
     * Banner label for artists with active exhibitions
     */
    currentlyShowing?: string | null;
    /**
     * Banner label on the News page for the latest post
     */
    recentlyPosted?: string | null;
    /**
     * Banner label on the Happenings page for the next event
     */
    comingUp?: string | null;
    /**
     * Caption above the "What's Happening" section on the homepage
     */
    upcoming?: string | null;
    /**
     * Label shown for currently active exhibitions
     */
    onNow?: string | null;
    /**
     * Label shown for the next upcoming exhibition
     */
    upNext?: string | null;
    /**
     * Label before the start date of a happening
     */
    opens?: string | null;
    /**
     * Label before the end date of a happening
     */
    closes?: string | null;
    /**
     * Fallback button text when a happening type name is not available
     */
    viewHappening?: string | null;
  };
  footer?: {
    sitemapTitle?: string | null;
    hoursTitle?: string | null;
    infoTitle?: string | null;
    newsletterTitle?: string | null;
  };
  search?: {
    artistsShowSearch?: boolean | null;
    happeningsShowSearch?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero?:
          | T
          | {
              type?: T;
              richText?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              media?: T;
            };
      };
  heroVideo?: T;
  heroVideoPoster?: T;
  missionIcon?: T;
  missionStatement?: T;
  missionCtaText?: T;
  missionCtaUrl?: T;
  featuredArtist?: T;
  featuredArtistImage?: T;
  featuredArtistCtaPrefix?: T;
  featuredArtistDescription?: T;
  visitSectionEnabled?: T;
  visitTitle?: T;
  visitDescription?: T;
  visitImage?: T;
  visitCtaText?: T;
  visitCtaUrl?: T;
  popupHeadline?: T;
  popupDescription?: T;
  popupButtonText?: T;
  popupSuccessMessage?: T;
  whatsHappeningEnabled?: T;
  whatsHappeningTitle?: T;
  whatsHappeningIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit_select".
 */
export interface VisitSelect<T extends boolean = true> {
  heroImage?: T;
  hours?:
    | T
    | {
        caption?: T;
        title?: T;
        description?: T;
        note?: T;
        specialHoursTitle?: T;
        specialHours?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  showAdmissionSection?: T;
  admission?:
    | T
    | {
        caption?: T;
        title?: T;
        description?: T;
        generalAdmissionTitle?: T;
        generalAdmissionDescription?: T;
        generalAdmissionFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        groupVisitTitle?: T;
        groupVisitDescription?: T;
        groupVisitFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  location?:
    | T
    | {
        caption?: T;
        title?: T;
        description?: T;
        addressLabel?: T;
        googleMapsUrl?: T;
        parkingLabel?: T;
        parkingDescription?: T;
        parkingFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        directions?:
          | T
          | {
              title?: T;
              content?: T;
              style?: T;
              id?: T;
            };
      };
  chesterton?:
    | T
    | {
        caption?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  dunelandCommunityEnabled?: T;
  dunelandCommunity?:
    | T
    | {
        caption?: T;
        title?: T;
        description?: T;
      };
  faqsSection?:
    | T
    | {
        caption?: T;
        title?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  privacyContent?: T;
  privacyLastUpdated?: T;
  cookiesContent?: T;
  cookiesLastUpdated?: T;
  termsContent?: T;
  termsLastUpdated?: T;
  landAcknowledgementContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-story_select".
 */
export interface OurStorySelect<T extends boolean = true> {
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  story?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  address?: T;
  phone?: T;
  email?: T;
  hours?: T;
  structuredHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  admission?: T;
  pageTitles?:
    | T
    | {
        artists?: T;
        happenings?: T;
        news?: T;
        visit?: T;
        ourStory?: T;
      };
  labels?:
    | T
    | {
        featuredArtist?: T;
        currentlyShowing?: T;
        recentlyPosted?: T;
        comingUp?: T;
        upcoming?: T;
        onNow?: T;
        upNext?: T;
        opens?: T;
        closes?: T;
        viewHappening?: T;
      };
  footer?:
    | T
    | {
        sitemapTitle?: T;
        hoursTitle?: T;
        infoTitle?: T;
        newsletterTitle?: T;
      };
  search?:
    | T
    | {
        artistsShowSearch?: T;
        happeningsShowSearch?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateImageSizes".
 */
export interface TaskGenerateImageSizes {
  input: {
    mediaId: string;
  };
  output: {
    sizesGenerated?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'artists';
          value: string | Artist;
        } | null)
      | ({
          relationTo: 'happenings';
          value: string | Happening;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}